const data = require('../../data/globalData')
/* Exibir a página de login, com a logo do facebook juntamente com o texto 
“O Facebook ajuda você a se conectar e compartilhar com as pessoas que fazem parte da sua vida.” ao lado deve ser exibido os inputs de email/telefone e senha, 
acessos a funcionalidades de recuperação de senha(link), criação de nova conta(button) e criar uma página(link); 
No rodapé deve ser  exibido um seletor de idiomas “favoritos” com possibilidade de adicionar outros idiomas a seção “favoritos”, 
logo abaixo devem ser exibidos microlinks de serviços e produtos do Facebook e ao fim deve ser exibido os direitos autorais  “copyright”.*/
module.exports = {

    '@tags': ['acesso-login'],

    before: function (browser) {
        browser.page.loginPage.login().navigate()
    },
    'Acesse a página de login facebook.com ': function (browser) {
        browser.page.loginPage.login()
            .assert.urlEquals("https://www.facebook.com/")
    },
    'Verificação de formulario de login email e senha': function (browser) {
        browser.page.loginPage.login()
            .assert.containsText('@titleMessage', 'O Facebook ajuda você a se conectar e compartilhar com as pessoas que fazem parte da sua vida.')
            .assert.containsText('@inputEmailNumber', "")
            .assert.attributeContains('@inputEmailNumber', 'placeholder', 'Email ou telefone')
            .assert.containsText('@inputPassword', "")
            .assert.attributeContains('@inputPassword', 'placeholder', 'Senha')
            .assert.visible('@buttonEntrar')
            .assert.containsText('@buttonEntrar', 'Entrar')
            .assert.containsText('@linkEsqueceuSenha', 'Esqueceu a senha?')
            .assert.attributeContains('@linkEsqueceuSenha', 'href', data.urls.urlEsqueceuSenha)
            .assert.visible('@buttonCriarNovaConta')
            .assert.containsText('@buttonCriarNovaConta', 'Criar nova conta')
            .assert.containsText('@linkCriarPagina', 'Criar uma Página')
            .assert.attributeContains('@linkCriarPagina', 'href', data.urls.urlNovaPagina)
    },
    'Verificação dados rodapé da pagina - Idiomas/Produtos/Direitos ': function (browser) {
        browser.page.loginPage.login()
            .assert.containsText('@listIdiomas', 'Português (Brasil)')
            .assert.containsText('@listIdiomasIngles', 'English (US)')
            .assert.attributeContains('@listIdiomasIngles', 'href', data.urls.urlIdiomaIngles)
            .assert.containsText('@listIdiomasEspanhol', 'Español')
            .assert.attributeContains('@listIdiomasEspanhol', 'href', data.urls.urlIdiomaEspanhol)
            .assert.containsText('@listIdiomasFrances', 'Français (France)')
            .assert.attributeContains('@listIdiomasFrances', 'href', data.urls.urlIdiomasFrances)
            .assert.containsText('@listIdiomasItaliano', 'Italiano')
            .assert.attributeContains('@listIdiomasItaliano', 'href', data.urls.urlIdiomasItaliano)
            .assert.containsText('@listIdiomasArabe', 'العربية')
            .assert.attributeContains('@listIdiomasArabe', 'href', data.urls.urlIdiomasArabe)
            .assert.containsText('@listIdiomasAlemao', 'Deutsch')
            .assert.attributeContains('@listIdiomasAlemao', 'href', data.urls.urlIdiomasAlemao)
            .assert.containsText('@listIdiomasIndiano', 'हिन्दी')
            .assert.attributeContains('@listIdiomasIndiano', 'href', data.urls.urlIdiomasIndiano)
            .assert.containsText('@listIdiomasChines', '中文(简体)')
            .assert.attributeContains('@listIdiomasChines', 'href', data.urls.urlIdiomasChines)
            .assert.containsText('@listIdiomasJapones', '日本語')
            .assert.attributeContains('@listIdiomasJapones', 'href', data.urls.urlIdiomasJapones)
            .assert.containsText('@footerCadastrese', 'Cadastre-se')
            .assert.attributeContains('@footerCadastrese', 'href', data.urls.urlFooterCadastrese)
            .assert.containsText('@footerEntrar', 'Entrar')
            .assert.attributeContains('@footerEntrar', 'href', data.urls.urlFooterEntrar)
            .assert.containsText('@footerMessenger', 'Messenger')
            .assert.attributeContains('@footerMessenger', 'href', data.urls.urlFooterMessenger)
            .assert.containsText('@footerFacebookLite', 'Facebook Lite')
            .assert.attributeContains('@footerFacebookLite', 'href', data.urls.urlFooterFacebookLite)
            .assert.containsText('@footerAssistir', 'Watch')
            .assert.attributeContains('@footerAssistir', 'href', data.urls.urlFooterAssistir)
            .assert.containsText('@footerPessoas', 'Pessoas')
            .assert.attributeContains('@footerPessoas', 'href', data.urls.urlFooterPessoas)
            .assert.containsText('@footerPaginas', 'Páginas')
            .assert.attributeContains('@footerPaginas', 'href', data.urls.urlFooterPaginas)
            .assert.containsText('@footerCategoriaPaginas', 'Categorias de Página')
            .assert.attributeContains('@footerCategoriaPaginas', 'href', data.urls.urlFooterCategoriaPaginas)
            .assert.containsText('@footerLocais1', 'Locais')
            .assert.attributeContains('@footerLocais1', 'href', data.urls.urlFooterLocais1)
            .assert.containsText('@footerJogos', 'Jogos')
            .assert.attributeContains('@footerJogos', 'href', data.urls.urlFooterJogos)
            .assert.containsText('@footerLocais', 'Locais')
            .assert.attributeContains('@footerLocais', 'href', data.urls.urlFooterLocais)
            .assert.containsText('@footerMarketPlace', 'Marketplace')
            .assert.attributeContains('@footerMarketPlace', 'href', data.urls.urlFooterMarketPlace)
            .assert.containsText('@footerFacebookPay', 'Facebook Pay')
            .assert.attributeContains('@footerFacebookPay', 'href', data.urls.urlFooterFacebookPay)
            .assert.containsText('@footerGrupos', 'Grupos')
            .assert.attributeContains('@footerGrupos', 'href', data.urls.urlFooterGrupos)
            .assert.containsText('@footerVagasEmprego', 'Vagas de emprego')
            .assert.attributeContains('@footerVagasEmprego', 'href', data.urls.urlFooterVagasEmprego)
            .assert.containsText('@footerOcultus', 'Oculus')
            .assert.attributeContains('@footerOcultus', 'href', data.urls.urlFooterOcultus)
            .assert.containsText('@footerPortal', 'Portal')
            .assert.attributeContains('@footerPortal', 'href', data.urls.urlFooterPortal)
            .assert.containsText('@footerInstagram', 'Instagram')
            .assert.attributeContains('@footerInstagram', 'href', data.urls.urlFooterInstagram)
            .assert.containsText('@footerLocal', 'Local')
            .assert.attributeContains('@footerLocal', 'href', data.urls.urlFooterLocal)
            .assert.containsText('@footerCampanhas', 'Campanhas de arrecadação de fundos')
            .assert.attributeContains('@footerCampanhas', 'href', data.urls.urlFooterCampanhas)
            .assert.containsText('@footerServicos', 'Serviços')
            .assert.attributeContains('@footerServicos', 'href', data.urls.urlFooterServicos)
            .assert.containsText('@footerCentralInf', 'Central de Informações de Votação')
            .assert.attributeContains('@footerCentralInf', 'href', data.urls.urlFooterCentralInf)
            .assert.containsText('@footerSobre', 'Sobre')
            .assert.attributeContains('@footerSobre', 'href', data.urls.urlFooterSobre)
            .assert.containsText('@footerCriarAnuncios', 'Criar anúncio')
            .assert.attributeContains('@footerCriarAnuncios', 'href', data.urls.urlFooterCriarAnuncios)
            .assert.containsText('@footerCriarPagina', 'Criar Página')
            .assert.attributeContains('@footerCriarPagina', 'href', data.urls.urlFooterCriarPagina)
            .assert.containsText('@footerDesenvolvedores', 'Desenvolvedores')
            .assert.attributeContains('@footerDesenvolvedores', 'href', data.urls.urlFooterDesenvolvedores)
            .assert.containsText('@footerCarreiras', 'Carreiras')
            .assert.attributeContains('@footerCarreiras', 'href', data.urls.urlFooterCarreiras)
            .assert.containsText('@footerPrivacidade', 'Privacidade')
            .assert.attributeContains('@footerPrivacidade', 'href', data.urls.urlFooterPrivacidade)
            .assert.containsText('@footerCookies', 'Cookies')
            .assert.attributeContains('@footerCookies', 'href', data.urls.urlFooterCookies)
            .assert.containsText('@footerEscolhaAnuncios', 'Escolhas para anúncios')
            .assert.attributeContains('@footerEscolhaAnuncios', 'href', data.urls.urlFooterEscolhaAnuncios)
            .assert.containsText('@footerTermos', 'Termos')
            .assert.attributeContains('@footerTermos', 'href', data.urls.urlFooterTermos)
            .assert.containsText('@footerAjuda', 'Ajuda')
            .assert.attributeContains('@footerAjuda', 'href', data.urls.urlFooterAjuda)
            .assert.containsText('@copyright', 'Facebook © 2021')
    },
    after: function (browser) {
        browser.end
    },

}
